// ES Modules - Exporting functions
import { getHolidays, filterHolidaysByMonth } from './project.js';

// Function to initialize the application
const initialize = () => {
    const countries = [ // Populate dropdown for Country
        //{country code, country name}
        {code: "af", name: "Afghanistan"},
        {code: "al", name: "Albania"},
        {code: "dz", name: "Algeria"},
        {code: "as", name: "American Samoa"},
        {code: "ad", name: "Andorra"},
        {code: "ao", name: "Angola"},
        {code: "ai", name: "Anguilla"},
        {code: "ag", name: "Antigua and Barbuda"},
        {code: "ar", name: "Argentina"},
        {code: "am", name: "Armenia"},
        {code: "aw", name: "Aruba"},
        {code: "au", name: "Australia"},
        {code: "at", name: "Austria"},
        {code: "az", name: "Azerbaijan"},
        {code: "bh", name: "Bahrain"},
        {code: "bd", name: "Bangladesh"},
        {code: "bb", name: "Barbados"},
        {code: "by", name: "Belarus"},
        {code: "be", name: "Belgium"},
        {code: "bz", name: "Belize"},
        {code: "bj", name: "Benin"},
        {code: "bm", name: "Bermuda"},
        {code: "bt", name: "Bhutan"},
        {code: "bo", name: "Bolivia"},
        {code: "ba", name: "Bosnia and Herzegovina"},
        {code: "bw", name: "Botswana"},
        {code: "br", name: "Brazil"},
        {code: "vg", name: "British Virgin Islands"},
        {code: "bn", name: "Brunei"},
        {code: "bg", name: "Bulgaria"},
        {code: "bf", name: "Burkina Faso"},
        {code: "bi", name: "Burundi"},
        {code: "cv", name: "Cabo Verde"},
        {code: "kh", name: "Cambodia"},
        {code: "cm", name: "Cameroon"},
        {code: "ca", name: "Canada"},
        {code: "ky", name: "Cayman Islands"},
        {code: "cf", name: "Central African Republic"},
        {code: "td", name: "Chad"},
        {code: "cl", name: "Chile"},
        {code: "cn", name: "China"},
        {code: "co", name: "Colombia"},
        {code: "km", name: "Comoros"},
        {code: "cg", name: "Congo"},
        {code: "cd", name: "Congo Democratic Republic"},
        {code: "ck", name: "Cook Islands"},
        {code: "cr", name: "Costa Rica"},
        {code: "ci", name: "Cote d'Ivoire"},
        {code: "hr", name: "Croatia"},
        {code: "cu", name: "Cuba"},
        {code: "cw", name: "Curaçao"},
        {code: "cy", name: "Cyprus"},
        {code: "cz", name: "Czech Republic"},
        {code: "dk", name: "Denmark"},
        {code: "dj", name: "Djibouti"},
        {code: "dm", name: "Dominica"},
        {code: "do", name: "Dominican Republic"},
        {code: "tl", name: "East Timor"},
        {code: "ec", name: "Ecuador"},
        {code: "eg", name: "Egypt"},
        {code: "sv", name: "El Salvador"},
        {code: "gq", name: "Equatorial Guinea"},
        {code: "er", name: "Eritrea"},
        {code: "ee", name: "Estonia"},
        {code: "et", name: "Ethiopia"},
        {code: "fk", name: "Falkland Islands"},
        {code: "fo", name: "Faroe Islands"},
        {code: "fj", name: "Fiji"},
        {code: "fi", name: "Finland"},
        {code: "fr", name: "France"},
        {code: "pf", name: "French Polynesia"},
        {code: "ga", name: "Gabon"},
        {code: "gm", name: "Gambia"},
        {code: "ge", name: "Georgia"},
        {code: "de", name: "Germany"},
        {code: "gh", name: "Ghana"},
        {code: "gi", name: "Gibraltar"},
        {code: "gr", name: "Greece"},
        {code: "gl", name: "Greenland"},
        {code: "gd", name: "Grenada"},
        {code: "gu", name: "Guam"},
        {code: "gt", name: "Guatemala"},
        {code: "gg", name: "Guernsey"},
        {code: "gn", name: "Guinea"},
        {code: "gw", name: "Guinea-Bissau"},
        {code: "gy", name: "Guyana"},
        {code: "ht", name: "Haiti"},
        {code: "va", name: "Holy See (Vatican City)"},
        {code: "hn", name: "Honduras"},
        {code: "hk", name: "Hong Kong"},
        {code: "hu", name: "Hungary"},
        {code: "is", name: "Iceland"},
        {code: "in", name: "India"},
        {code: "id", name: "Indonesia"},
        {code: "ir", name: "Iran"},
        {code: "iq", name: "Iraq"},
        {code: "ie", name: "Ireland"},
        {code: "im", name: "Isle of Man"},
        {code: "il", name: "Israel"},
        {code: "it", name: "Italy"},
        {code: "jm", name: "Jamaica"},
        {code: "jp", name: "Japan"},
        {code: "je", name: "Jersey"},
        {code: "jo", name: "Jordan"},
        {code: "kz", name: "Kazakhstan"},
        {code: "ke", name: "Kenya"},
        {code: "ki", name: "Kiribati"},
        {code: "xk", name: "Kosovo"},
        {code: "kw", name: "Kuwait"},
        {code: "kg", name: "Kyrgyzstan"},
        {code: "la", name: "Laos"},
        {code: "lv", name: "Latvia"},
        {code: "lb", name: "Lebanon"},
        {code: "ls", name: "Lesotho"},
        {code: "lr", name: "Liberia"},
        {code: "ly", name: "Libya"},
        {code: "li", name: "Liechtenstein"},
        {code: "lt", name: "Lithuania"},
        {code: "lu", name: "Luxembourg"},
        {code: "mo", name: "Macau"},
        {code: "mg", name: "Madagascar"},
        {code: "mw", name: "Malawi"},
        {code: "my", name: "Malaysia"},
        {code: "mv", name: "Maldives"},
        {code: "ml", name: "Mali"},
        {code: "mt", name: "Malta"},
        {code: "mh", name: "Marshall Islands"},
        {code: "mq", name: "Martinique"},
        {code: "mr", name: "Mauritania"},
        {code: "mu", name: "Mauritius"},
        {code: "yt", name: "Mayotte"},
        {code: "mx", name: "Mexico"},
        {code: "fm", name: "Micronesia"},
        {code: "md", name: "Moldova"},
        {code: "mc", name: "Monaco"},
        {code: "mn", name: "Mongolia"},
        {code: "me", name: "Montenegro"},
        {code: "ms", name: "Montserrat"},
        {code: "ma", name: "Morocco"},
        {code: "mz", name: "Mozambique"},
        {code: "mm", name: "Myanmar"},
        {code: "na", name: "Namibia"},
        {code: "nr", name: "Nauru"},
        {code: "np", name: "Nepal"},
        {code: "nl", name: "Netherlands"},
        {code: "nc", name: "New Caledonia"},
        {code: "nz", name: "New Zealand"},
        {code: "ni", name: "Nicaragua"},
        {code: "ne", name: "Niger"},
        {code: "ng", name: "Nigeria"},
        {code: "kp", name: "North Korea"},
        {code: "mk", name: "North Macedonia"},
        {code: "mp", name: "Northern Mariana Islands"},
        {code: "no", name: "Norway"},
        {code: "om", name: "Oman"},
        {code: "pk", name: "Pakistan"},
        {code: "pw", name: "Palau"},
        {code: "pa", name: "Panama"},
        {code: "pg", name: "Papua New Guinea"},
        {code: "py", name: "Paraguay"},
        {code: "pe", name: "Peru"},
        {code: "ph", name: "Philippines"},
        {code: "pl", name: "Poland"},
        {code: "pt", name: "Portugal"},
        {code: "pr", name: "Puerto Rico"},
        {code: "qa", name: "Qatar"},
        {code: "re", name: "Reunion"},
        {code: "ro", name: "Romania"},
        {code: "ru", name: "Russia"},
        {code: "rw", name: "Rwanda"},
        {code: "sh", name: "Saint Helena"},
        {code: "kn", name: "Saint Kitts and Nevis"},
        {code: "lc", name: "Saint Lucia"},
        {code: "mf", name: "Saint Martin"},
        {code: "pm", name: "Saint Pierre and Miquelon"},
        {code: "vc", name: "Saint Vincent and the Grenadines"},
        {code: "ws", name: "Samoa"},
        {code: "sm", name: "San Marino"},
        {code: "st", name: "Sao Tome and Principe"},
        {code: "sa", name: "Saudi Arabia"},
        {code: "sn", name: "Senegal"},
        {code: "rs", name: "Serbia"},
        {code: "sc", name: "Seychelles"},
        {code: "sl", name: "Sierra Leone"},
        {code: "sg", name: "Singapore"},
        {code: "sx", name: "Sint Maarten"},
        {code: "sk", name: "Slovakia"},
        {code: "si", name: "Slovenia"},
        {code: "sb", name: "Solomon Islands"},
        {code: "so", name: "Somalia"},
        {code: "za", name: "South Africa"},
        {code: "kr", name: "South Korea"},
        {code: "ss", name: "South Sudan"},
        {code: "es", name: "Spain"},
        {code: "lk", name: "Sri Lanka"},
        {code: "bl", name: "St. Barts"},
        {code: "sd", name: "Sudan"},
        {code: "sr", name: "Suriname"},
        {code: "se", name: "Sweden"},
        {code: "ch", name: "Switzerland"},
        {code: "sy", name: "Syria"},
        {code: "tw", name: "Taiwan"},
        {code: "tj", name: "Tajikistan"},
        {code: "tz", name: "Tanzania"},
        {code: "th", name: "Thailand"},
        {code: "bs", name: "The Bahamas"},
        {code: "tg", name: "Togo"},
        {code: "to", name: "Tonga"},
        {code: "tt", name: "Trinidad and Tobago"},
        {code: "tn", name: "Tunisia"},
        {code: "tr", name: "Turkey"},
        {code: "tm", name: "Turkmenistan"},
        {code: "tc", name: "Turks and Caicos Islands"},
        {code: "tv", name: "Tuvalu"},
        {code: "vi", name: "US Virgin Islands"},
        {code: "ug", name: "Uganda"},
        {code: "ua", name: "Ukraine"},
        {code: "ae", name: "United Arab Emirates"},
        {code: "gb", name: "United Kingdom"},
        {code: "us", name: "United States"},
        {code: "uy", name: "Uruguay"},
        {code: "uz", name: "Uzbekistan"},
        {code: "vu", name: "Vanuatu"},
        {code: "ve", name: "Venezuela"},
        {code: "vn", name: "Vietnam"},
        {code: "wf", name: "Wallis and Futuna"},
        {code: "ye", name: "Yemen"},
        {code: "zm", name: "Zambia"},
        {code: "zw", name: "Zimbabwe"},
        {code: "sz", name: "eSwatini"}        
    ];

    // Populate the country selection dropdown
    const countryElement = document.getElementById('country');
    countryElement.innerHTML = '<option value=""> </option>';

    countries.forEach(country => {
        const option = document.createElement('option');
        option.value = country.code;
        option.text = country.name;
        countryElement.appendChild(option);
    });

    // Add event listeners for button clicks and month filter changes
    document.getElementById('getHolidaysButton').addEventListener('click', getHolidays);
    document.getElementById('monthFilter').addEventListener('change', filterHolidaysByMonth);
}

// Run the initialization when the DOM is ready
document.addEventListener('DOMContentLoaded', initialize);